language: swift
osx_image: xcode12.2

jobs:
  include:
    - stage: "Tests/Lint/Build" 
      name: "Frontend Build & Test & swiftlint"
      podfile: Podfile
      before_install: pod repo update
      script:
        - xcodebuild -workspace Doodle2Gather.xcworkspace -scheme Doodle2Gather -destination 'platform=iOS Simulator,OS=14.2,name=iPad Air (4th generation)' build test
        - swiftlint
    - name: "Backend Build"
      script: cd WebsocketBackend && swift build
